### ISSUE TITLE
Support  unicode in tenantId

### ISSUE THREAD

**Issue by gennom** [cuba-platform/multitenancy-addon#13]
Now unicode is not supported in tenantId. Because of this, you have to control the input characters in the "Tenant ID" field on the Tenant creation screen.
Or is it specifically so done?

**Comment by NikitaShchienko** [comment]
Hi @gennom,

This was done on purpose.

**Comment by gennom** [comment]
> Hi @gennom,
> 
> This was done on purpose.

Fine! Thank you very much!
