### ISSUE TITLE
Not work using SQLServer

### ISSUE THREAD

**Issue by stefanofalasca** [cuba-platform/multitenancy-addon#17]
![image](https://user-images.githubusercontent.com/1249181/54010380-d955d600-416e-11e9-990a-3112e143a81f.png)

**Comment by zaharchenko-evgeny** [comment]
Hi @stefanofalasca,

This issue should be fixed in https://github.com/cuba-platform/multitenancy-addon/issues/15 ticket

Regards,
Evgeny
