### ISSUE TITLE
Unable to compile the multitenancy-addon when the User is extended....

### ISSUE THREAD

**Issue by vimalkumar010** [cuba-platform/multitenancy-addon#19]
### Environment

- Platform version: 6.10-SNAPSHOT
- Addon version: 1.2.0

- Client type: 
- Browser: 
- Database: 
- Operating system: 

### Description of the bug or enhancement

-Unable to compile the project with multitenancy-addon, when the User is extended in the Project.

**Comment by zaharchenko-evgeny** [comment]
Hi @vimalkumar010,

Please try to extend `User` in your project from `TenantUser`

**Comment by vimalkumar010** [comment]
Even though extending the User in my project with TenantUser. I'm unable to replace the parent... If i replace the parent then the project is not starting....

**Comment by zaharchenko-evgeny** [comment]
Hi @vimalkumar010,

Please check possible solution in the last message in our forum https://www.cuba-platform.com/discuss/t/user-cant-be-extended-if-multi-tenancy-addon-is-used/9295/9

Regards,
Evgeny
