### ISSUE TITLE
Tenant users created in sub-sub-access groups lose tenant restrictions

### ISSUE THREAD

**Issue by igor-korotkov** [cuba-platform/multitenancy-addon#2]
If we have an access group structure like this:

- Company
  - Tenant 1
    - Group 1
      - Group 2         

Users in Group 2 **lose all tenant restrictions**

The problem is in MultiTenancySecurityHandler#findGroupTenant
The query for group hierarchy doesn't go through the whole hierarchy to find the tenant id as it should.

**Comment by ivan-osipov** [comment]
There was a bug in user creation, described issue does not reproduce after user creation bug fix
