### ISSUE TITLE
Creating a software role for the tenant administrator

### ISSUE THREAD

**Issue by NikitaShchienko** [cuba-platform/multitenancy-addon#44]

**Comment by zaharchenko-evgeny** [comment]
# Predefined roles

- **tenant-admin-role** - allows user to configure tenants
- **default-tenant-role** - default tenant user role

**Comment by zaharchenko-evgeny** [comment]
A predefined role can be configured as a default tenant user role

**Comment by dmakagonova** [comment]
addon 2.0-SNAPSHOT, cuba 7.2.4

1. Run demo / empty project with addon
2. Login as admin
3. Click Tenant management
4. Tenants
5. Click Create

Expected result: window for edit
Actual result: 
![2020-05-12_16-56-42](https://user-images.githubusercontent.com/39261656/81705645-4f934e00-9480-11ea-88a4-29b5f3167619.png)
