### ISSUE TITLE
CUBA_SDBMT_TENANT table is not dropped after add-on deleting

### ISSUE THREAD

**Issue by owlet1997** [cuba-platform/multitenancy-addon#64]
based on forum's [question](https://forum.cuba-platform.com/t/elastic-beanstalk-issues-with-multitenancy-addon/15533/9) 

### Environment

CUBA Platform version: 7.2.14
CUBA Studio plugin version: 15.5-211
IntelliJ version: IntelliJ IDEA 2021.2 (Ultimate Edition)
Operating system: Ubuntu 20.04 LTS
Add-on version: 2.0.2

### TC:
1. Create new project 
2. Set main datastore type PostgreSQL
3. Add the Multitenancy add-on from the Marketplace
4. Run app -> update database -> stop app
5. Remove the Multitenancy add-on
6. Run app -> update database
7. Open database tables in IDEA or DBeaver

**AR:**
CUBA_SDBMT_TENANT table is not dropped after add-on deleting
![image](https://user-images.githubusercontent.com/45730069/129668019-fec0dc19-92f0-41d3-bfde-267c6b329a36.png)

**ER:**
Add-on's tables should be removed after add-on deleting

**Comment by andreysubbotin** [comment]
@owlet1997, it's not valid. Any CUBA/Jmix addon does not provide the ability to automatically delete tables on addon deleting.
